# Generated by Django 5.2 on 2025-04-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask_app", "0003_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="(No title)", max_length=80),
        ),
    ]
