# Generated by Django 5.2 on 2025-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0004_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='light_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='images/pf_default.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
