# Generated by Django 5.2 on 2025-05-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0005_profile_bio_profile_light_mode_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='light_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.CharField(default='', max_length=500),
        ),
    ]
