# Generated by Django 5.2 on 2025-05-02 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0005_comment'),
        ('ask_app', '0006_remove_profile_light_mode_profile_dark_mode_and_more'),
    ]

    operations = [
    ]
