# Generated by Django 5.2 on 2025-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0007_merge_20250502_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
