# Generated by Django 5.2 on 2025-05-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0008_alter_profile_picture'),
        ('ask_app', '0009_likedcomment_comment_likes'),
    ]

    operations = [
    ]
