# Generated by Django 5.2 on 2025-05-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ask_app", "0010_merge_20250506_1548"),
        ("ask_app", "0011_category_postcategory_post_categories"),
    ]

    operations = []
