# Generated by Django 5.2 on 2025-05-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_app', '0012_merge_20250508_0237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
