# Generated by Django 5.2 on 2025-05-08 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ask_app", "0013_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="categories",
        ),
    ]
