# Generated by Django 5.2 on 2025-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ask_app", "0014_remove_post_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="posts",
                through="ask_app.PostCategory",
                to="ask_app.category",
            ),
        ),
    ]
